export default  {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  START_LOAD: '_START_LOAD',
  FINISH_LOAD: '_FINISH_LOAD',
  GET_ERRORS: 'GET_ERRORS',
  GET_CURRENT_PRODUCTS: 'GET_CURRENT_PRODUCTS',
  GET_PRODUCTS: 'GET_PRODUCTS',
  CLEAR_PRODUCT: 'CLEAR_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
}
